# Generated by Django 3.1.7 on 2021-05-11 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='task',
            name='initial_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
