# Generated by Django 3.1.7 on 2021-05-11 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscore', '0002_auto_20210511_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 12, 14, 15, 37, 964148)),
        ),
    ]
