# Generated by Django 3.1.7 on 2021-05-11 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mscore', '0003_auto_20210511_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='task',
            name='initial_date',
        ),
    ]
