# Generated by Django 3.1.7 on 2021-05-11 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscore', '0004_auto_20210511_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 12, 14, 16, 18, 181519)),
        ),
        migrations.AddField(
            model_name='task',
            name='initial_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
