# Generated by Django 3.1.7 on 2021-05-16 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mscore.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mscore', '0005_auto_20210511_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='users',
            field=models.ManyToManyField(related_name='spaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='space',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='owned_spaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, default=mscore.models.tomorrow),
        ),
    ]
