# Generated by Django 3.1.7 on 2021-02-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscore', '0005_auto_20210219_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
