# Generated by Django 3.1.7 on 2021-05-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mscore', '0006_auto_20210516_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='users',
            new_name='members',
        ),
    ]
