# Generated by Django 3.1.7 on 2021-02-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscore', '0006_task_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
