# Generated by Django 3.1.7 on 2021-02-27 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mscore', '0007_auto_20210221_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('A', 'Approval'), ('W', 'Waiting'), ('P', 'Progressing'), ('R', 'Ready'), ('C', 'Correction')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='space',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
