# Generated by Django 3.1.7 on 2021-05-22 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mscore', '0007_auto_20210516_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-deadline', 'status']},
        ),
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='mscore.task'),
        ),
        migrations.AlterField(
            model_name='space',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='spaces', to=settings.AUTH_USER_MODEL),
        ),
    ]
