# Generated by Django 3.1.7 on 2021-05-22 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mscore', '0008_auto_20210522_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='mscore.task'),
        ),
    ]
