# Generated by Django 3.1.7 on 2021-05-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscore', '0009_auto_20210522_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_nested',
            field=models.BooleanField(default=False),
        ),
    ]
